version: '3.9'
services:

  web:
    build: .
    ports:
      - "80:80"
    environment:
      - PORT=80
      - SESSION_SECRET=funny
      - DB_URL=mongodb://mongo:27017/docker-node-mongo/carsvp

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: carsvp
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: